title: Blog Bibliotheks- und Archivinformatik
author: Jannik
email: jannik.christen@fhgr.ch
description: > # this means to ignore newlines
  Vorlage für ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020

# social links
github_username:  TonyTestimony

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
